# -*- coding: utf-8 -*-
"""Red_Wine_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuMRHMa-jL3-k9O5JRPms3IGITYkwtJy
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('winequality-red.csv')
df

df.info()

df.describe()

df.shape

df.columns

df['quality'].unique()

df['quality'].value_counts()

df.isnull().sum()

df[df.duplicated()]

#Remove the duplicates

df.drop_duplicates(inplace=True)

df.shape

df.corr()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(),annot= True)

df.head()

#Visualization

df.quality.value_counts().plot(kind='bar')
plt.xlabel('Quality')
plt.ylabel('Count')
plt.title('Quality Count')

for column in df.columns:
  sns.histplot(df[column],kde=True)

sns.histplot(df['alcohol'],kde=True)

sns.pairplot(df)

#Categorical Plot

sns.catplot(x='quality',y='alcohol',data=df,kind='box')

#Removing Outliers

minimum,Q1,median,Q3,maximum  = np.quantile(df['alcohol'],[0,0.25,0.5,0.75,1])
print('Minimum: ',minimum)
print('Q1: ',Q1)
print('Median: ',median)
print('Q3: ',Q3)
print('Maximum: ',maximum)

IQR = Q3 - Q1
print('IQR: ', IQR)

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print('Lower bound: ', lower_bound)
print('Upper bound: ', upper_bound)

outliers = df[(df['alcohol'] < lower_bound) | (df['alcohol'] > upper_bound)]
print('Outliers in alcohol column:')
display(outliers)

#Remove the outliers

df.drop(outliers.index, inplace=True)

df.shape

sns.boxplot(x='quality', y='alcohol', data=df)

